---
title: "Getting Started with BayesianFitForecast"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Getting Started with BayesianFitForecast}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

## Introduction

**BayesianFitForecast** provides robust tools for parameter estimation and forecasting with epidemiological models. These tools are designed to streamline the process of analyzing epidemiological data using Bayesian inference. Detailed guidance on how to set up an option file can be found in the documentation available here: [https://arxiv.org/abs/2411.05371](https://arxiv.org/abs/2411.05371).

---

## Basic Usage

### Running the MCMC Analysis

Below is a demonstration of how to set up and run the MCMC analysis, followed by analyzing the results.

```{r, eval=FALSE}
# Specify the path to the data file (for Run_analyzeResults). The data file will be generated by Run_MCMC.

data_file <- system.file("extdata", package = "BayesianFitForecast")

# Specify the path to the option file.
option_file <- system.file("extdata", "option.R", 
                           package = "BayesianFitForecast")

# Specify the path to the Excel file including the reported data.
excel_file <- system.file("extdata", "SanFrancisco.xlsx", 
                          package = "BayesianFitForecast") 
# Specify the path to save the results. By default, it is set to the temporary path. 
output_path <- tempdir()

# Run the MCMC analysis. It generates the .Rdata file (data_file).
Run_MCMC(option_file, excel_file, output_path)

# Analyze the results. It generates all results files within a folder. 
Run_analyzeResults(data_file, option_file, excel_file, output_path)

# Please note that you can specify any address to data_file, option_file, excel_file, and output_path.
